# Full project title with acronymn
project: ""
# Short title
title: ""
# Acronym
acronym: ""
keywords: "key1, key2, key3"
funded_by: ""
call_details: ""
# URL with call details
funding_url: ""
# Project reference number
project_reference:
# Start date (ISO 8601)
from:
# End date (ISO 8601)
to:
# One line summarising primary project objective
objective: <
 Do some amazing things and tell everyone about it.
# 1-3 lines giving purpose of project 
purpose: <
 The project will do some amazing things by defining specifications for stuff,
 developing cool stuff and producing prototype stuff.
# Summary or abstract describing the project
description: <
 The project will do some amazing things by defining specifications for stuff,
 developing cool stuff and producing prototype stuff. Furthermore, we will tell
 everyone about it and release our cool stuff as open source code.
# URL project website
url:  ""
# project twitter account
twitter: ""
# project facebook page
facebook: ""
# total cost of project
total_cost: ""
EU_contribution: ""
cordis_url: ""
coordinated_in: ""
# official name of coordinator institution
coordinator: ""
# official name of partner institutions
participants:
  - ""
  - ""
